### ISSUE TITLE
Compile user material subroutine only once 

### ISSUE THREAD

**Issue by abcdvemm** [KnutAM/MaterialModels#2]
Which .nb file in each directory should be firstly used, in order to compile each user material subroutine only once?

Best

**Comment by KnutAM** [comment]
In order to compile the model you do not need to use the .nb files, you can just use the python scripts in the script folder. 
The .nb files are used to modify the material models and require the AceGen plugin. To compile a single subroutine you can specify a model class name (i.e. folder in the models directory) followed by the number that represents that particular model (in abaqus_compile_files.txt or cmake_compile_models.txt in that model class' src directory). 
(If you really want to modify the nb files, they are normally setup to use the main.nb file as the base file containing the settings as to what variant of the model to build sources for)
